const transferNumber = (number) => {
    switch (number) {
        case 'negative five':
            return '-5'
        case 'negative four':
            return '-4'
        case 'negative three':
            return '-3'
        case 'negative two':
            return '-2'
        case 'negative one':
            return '-1'
        case 'zero':
            return '0'
        case 'one':
            return '1'
        case 'two':
            return '2'
        case 'three':
            return '3'
        case 'four':
            return '4'
        case 'five':
            return '5'
        case 'six':
            return '6'
        case 'seven':
            return '7'
        case 'eight':
            return '8'
        case 'nine':
            return '9'
        case 'ten':
            return '10'
        case 'eleven':
            return '11'
        case 'twelve':
            return '12'
        case 'thirteen':
            return '13'
        case 'fourteen':
            return '14'
        case 'fifteen':
            return '15'
        case '負五':
            return '-5'
        case '負四':
            return '-4'
        case '負三':
            return '-3'
        case '負二':
            return '-2'
        case '負一':
            return '-1'
        case '零':
            return '0'
        case '一':
            return '1'
        case '二':
            return '2'
        case '三':
            return '3'
        case '四':
            return '4'
        case '五':
            return '5'
        case '六':
            return '6'
        case '七':
            return '7'
        case '八':
            return '8'
        case '九':
            return '9'
        case '十':
            return '10'
        case '十一':
            return '11'
        case '十二':
            return '12'
        case '十三':
            return '13'
        case '十四':
            return '14'
        case '十五':
            return '15'
        case '一一':
            return '11'
        case '一二':
            return '12'
        case '一三':
            return '13'
        case '一四':
            return '14'
        case '一五':
            return '15'
        case '一六':
            return '16'
        case '一七':
            return '17'
        case '一八':
            return '18'
        case '二一':
            return '21'
        case '二二':
            return '22'
        case '二三':
            return '23'
        case '二四':
            return '24'
        case '二五':
            return '25'
        case '二六':
            return '26'
        case '二七':
            return '27'
        case '二八':
            return '28'
        case '三一':
            return '31'
        case '三二':
            return '32'
        case '三三':
            return '33'
        case '三四':
            return '34'
        case '三五':
            return '35'
        case '三六':
            return '36'
        case '三七':
            return '37'
        case '三八':
            return '38'
        case '四一':
            return '41'
        case '四二':
            return '42'
        case '四三':
            return '43'
        case '四四':
            return '44'
        case '四五':
            return '45'
        case '四六':
            return '46'
        case '四七':
            return '47'
        case '四八':
            return '48'
        default:
            return false
    }
}

export default transferNumber